config/routes.rb
IndividualProject2::Application.routes.draw do
  resources :orders

  resources :tickets

  resources :menus

end

app/models/menu.rb
class Menu < ActiveRecord::Base
  attr_accessible :MenuItem, :MenuPrice
  has_many :orders
  has_many :tickets, through: :orders
  belongs_to :ticket
end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :Menu
  belongs_to :Ticket
   attr_accessible :title, :body
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :CustomerName, :TicketStatus, :TicketTotal, :quantity
  has_many :orders
  has_many :orders, through: :tickets
  belongs_to :menu
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @menus }
    end
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
    @menu = Menu.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/new
  # GET /menus/new.json
  def new
    @menu = Menu.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @menu }
    end
  end

  # GET /menus/1/edit
  def edit
    @menu = Menu.find(params[:id])
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(params[:menu])

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: 'Menu was successfully created.' }
        format.json { render json: @menu, status: :created, location: @menu }
      else
        format.html { render action: "new" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /menus/1
  # PUT /menus/1.json
  def update
    @menu = Menu.find(params[:id])

    respond_to do |format|
      if @menu.update_attributes(params[:menu])
        format.html { redirect_to @menu, notice: 'Menu was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    respond_to do |format|
      format.html { redirect_to menus_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndividualProject2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "Menus", menus_path %>
<%= link_to "Tickets", tickets_path %>
<%= link_to "Orders", orders_path %>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :MenuItem %><br />
    <%= f.text_field :MenuItem %>
  </div>
  <div class="field">
    <%= f.label :MenuPrice %><br />
    <%= f.text_field :MenuPrice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1>Editing menu</h1>

<%= render 'form' %>

<%= link_to 'Show', @menu %> |
<%= link_to 'Back', menus_path %>

app/views/menus/index.html.erb
<h1>Listing menus</h1>

<table>
  <tr>
    <th>Menuitem</th>
    <th>Menuprice</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @menus.each do |menu| %>
  <tr>
    <td><%= menu.MenuItem %></td>
    <td><%= menu.MenuPrice %></td>
    <td><%= link_to 'Show', menu %></td>
    <td><%= link_to 'Edit', edit_menu_path(menu) %></td>
    <td><%= link_to 'Destroy', menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Menu', new_menu_path %>

app/views/menus/new.html.erb
<h1>New menu</h1>

<%= render 'form' %>

<%= link_to 'Back', menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menuitem:</b>
  <%= @menu.MenuItem %>
</p>

<p>
  <b>Menuprice:</b>
  <%= @menu.MenuPrice %>
</p>


<%= link_to 'Edit', edit_menu_path(@menu) %> |
<%= link_to 'Back', menus_path %>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Menu %><br />
    <%= f.text_field :Menu %>
  </div>
  <div class="field">
    <%= f.label :Ticket %><br />
    <%= f.text_field :Ticket %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <tr>
    <th>Menu</th>
    <th>Ticket</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.Menu %></td>
    <td><%= order.Ticket %></td>
    <td><%= link_to 'Show', order %></td>
    <td><%= link_to 'Edit', edit_order_path(order) %></td>
    <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Menu:</b>
  <%= @order.Menu %>
</p>

<p>
  <b>Ticket:</b>
  <%= @order.Ticket %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :CustomerName %><br />
    <%= f.text_field :CustomerName %>
  </div>
    <div class="field">
      <%= f.label :quantity %><br />
      <%= f.number_field :quantity %>
    </div>

  <div class="field">
    <%= f.label :TicketStatus %><br />
    <%= f.select(:TicketStatus,[["Completed","Completed"],["Paid","Paid"],["Unpaid","Unpaid"]])  %>
  </div>


  <div class="field">
    <%= f.label :TicketTotal %><br />
    <%= f.text_field :TicketTotal %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <tr>
    <th>Customername</th>

    <th>Ticketstatus</th>
    <th>Tickettotal</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tickets.each do |ticket| %>
  <tr>
    <td><%= ticket.CustomerName %></td>

    <td><%= ticket.TicketStatus %></td>
    <td><%= ticket.TicketTotal %></td>
    <td><%= link_to 'Show', ticket %></td>
    <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
    <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Customername:</b>
  <%= @ticket.CustomerName %>
</p>



<p>
  <b>Ticketstatus:</b>
  <%= @ticket.TicketStatus %>
</p>

<p>
  <b>Tickettotal:</b>
  <%= @ticket.TicketTotal %>
</p>


<p>
  <b>Quantity:</b>
  <%= @ticket.quantity %>
</p>
<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>